[04:01:44.646022] Model params:
 {
    "accum_iter": 1,
    "batch_size": 8,
    "blr": 0.0001,
    "clip_grad": 5.0,
    "layer_decay": 0.75,
    "lr": 3.125e-06,
    "min_lr": 1e-06,
    "model_name": "part_ae_d8_m8_l32",
    "warmup_epochs": 1,
    "weight_decay": 0.05
}
[04:01:44.646407] Start training for [5] epochs, from epoch [0].
[04:01:45.260985] Epoch: [0]  [ 0/64]  eta: 0:00:37  loss_vol: 0.6951 (0.6951)  loss_near: 0.0694 (0.0694)  loss_kl: 0.0001 (0.0001)  acc: 0.4939 (0.4939)  iou: 0.3682 (0.3682)  time: 0.5916  data: 0.0022  max mem: 1634
[04:01:58.718465] Epoch: [0]  [50/64]  eta: 0:00:03  loss_vol: 0.6934 (0.6939)  loss_near: 0.0693 (0.0694)  loss_kl: 0.0001 (0.0001)  acc: 0.4987 (0.4990)  iou: 0.2549 (0.2540)  time: 0.2699  data: 0.0014  max mem: 1634
[04:02:02.181732] Epoch: [0]  [63/64]  eta: 0:00:00  loss_vol: 0.6934 (0.6938)  loss_near: 0.0693 (0.0694)  loss_kl: 0.0000 (0.0001)  acc: 0.4987 (0.4994)  iou: 0.2493 (0.2474)  time: 0.2698  data: 0.0014  max mem: 1634
[04:02:02.181978] Epoch: [0] Total time: 0:00:17 (0.2740 s / it)
[04:02:02.182113] Averaged stats: loss_vol: 0.6934 (0.6938)  loss_near: 0.0693 (0.0694)  loss_kl: 0.0000 (0.0001)  acc: 0.4987 (0.4994)  iou: 0.2493 (0.2474)
[04:02:02.772049] [04:02:02.772296] [04:02:02.772398] [04:02:02.772487] [04:02:02.772571]
Traceback (most recent call last):
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 394, in <module>
    main(args)
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 370, in main
    train_model(
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 261, in train_model
    data_loader_val.set_epoch(epoch)
AttributeError: 'DataLoader' object has no attribute 'set_epoch'
Traceback (most recent call last):
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 394, in <module>
    main(args)
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 370, in main
    train_model(
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 261, in train_model
    data_loader_val.set_epoch(epoch)
AttributeError: 'DataLoader' object has no attribute 'set_epoch'
