[04:47:51.956724] Model params:
 {
    "accum_iter": 1,
    "batch_size": 8,
    "blr": 0.0001,
    "clip_grad": 5.0,
    "layer_decay": 0.75,
    "lr": 3.125e-06,
    "min_lr": 1e-06,
    "model_name": "part_ae_d8_m8_l32",
    "warmup_epochs": 1,
    "weight_decay": 0.05
}
[04:47:51.956949] Start training for [5] epochs, from epoch [0].
[04:47:52.612868] Epoch: [0]  [0/2]  eta: 0:00:01  loss_vol: 0.6943 (0.6943)  loss_near: 0.0694 (0.0694)  loss_kl: 0.0001 (0.0001)  acc: 0.5001 (0.5001)  iou: 0.3740 (0.3740)  time: 0.6540  data: 0.0522  max mem: 1634
[04:47:52.880025] Epoch: [0]  [1/2]  eta: 0:00:00  loss_vol: 0.6943 (0.6945)  loss_near: 0.0694 (0.0694)  loss_kl: 0.0001 (0.0001)  acc: 0.4994 (0.4998)  iou: 0.3740 (0.3741)  time: 0.4603  data: 0.0270  max mem: 1634
[04:47:52.904800] Epoch: [0] Total time: 0:00:00 (0.4732 s / it)
[04:47:52.905204] Averaged stats: loss_vol: 0.6943 (0.6945)  loss_near: 0.0694 (0.0694)  loss_kl: 0.0001 (0.0001)  acc: 0.4994 (0.4998)  iou: 0.3740 (0.3741)
[04:47:57.759399] [04:47:57.759778] [04:47:57.759964] [04:47:57.760106] [04:47:57.760289]
Traceback (most recent call last):
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 425, in <module>
    main(args)
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 401, in main
    train_model(
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 261, in train_model
    data_loader_val.set_epoch(epoch)
AttributeError: 'DataLoader' object has no attribute 'set_epoch'
Traceback (most recent call last):
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 425, in <module>
    main(args)
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 401, in main
    train_model(
  File "/home/slimhy/Documents/PADS/code/main_part_ae.py", line 261, in train_model
    data_loader_val.set_epoch(epoch)
AttributeError: 'DataLoader' object has no attribute 'set_epoch'
