master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
| distributed init (rank 6): env://, gpu 6
| distributed init (rank 3): env://, gpu 3
| distributed init (rank 4): env://, gpu 4
| distributed init (rank 0): env://, gpu 0
| distributed init (rank 2): env://, gpu 2
| distributed init (rank 5): env://, gpu 5
| distributed init (rank 1): env://, gpu 1
| distributed init (rank 7): env://, gpu 7
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2759349 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2759350 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2759351 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2759352 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2759353 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2759354 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2759355 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 7 (pid: 2759356) of binary: /home/slimhy/conda/envs/shape2vecset/bin/python3.10
Traceback (most recent call last):
  File "/home/slimhy/conda/envs/shape2vecset/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
code/main_node2node.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-29_01:30:22
  host      : gpu213-14.ibex.kaust.edu.sa
  rank      : 7 (local_rank: 7)
  exitcode  : -9 (pid: 2759356)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 2759356
========================================================
slurmstepd: error: Detected 1 oom_kill event in StepId=31898610.batch. Some of the step tasks have been OOM Killed.
