WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
| distributed init (rank 2): env://, gpu 2
| distributed init (rank 3): env://, gpu 3
| distributed init (rank 0): env://, gpu 0
| distributed init (rank 1): env://, gpu 1
[01:01:05.244777] Input args:
 {
    "accum_iter": 1,
    "ae": "kl_d512_m512_l8",
    "ae_pth": "output/graph_edit/ae/ae_m512.pth",
    "alt_ae_embeds": "pc_ae",
    "batch_size": 32,
    "blr": 0.0001,
    "clip_grad": 3.0,
    "data_path": "/ibex/user/slimhy/ShapeWalk_RND/",
    "data_type": "release",
    "dataset": "graphedits",
    "debug_mode": false,
    "debug_with_forward": false,
    "device": "cuda",
    "dist_backend": "nccl",
    "dist_eval": true,
    "dist_on_itp": false,
    "dist_url": "env://",
    "distributed": true,
    "epochs": 800,
    "eval": false,
    "exp_name": "mlp_mapper_bert_l8_pcae",
    "fetch_keys": false,
    "ft_bert": false,
    "gpu": 0,
    "intensity_loss": false,
    "is_diff": false,
    "is_mlp": true,
    "is_nrl_listener": false,
    "layer_decay": 0.75,
    "local_rank": -1,
    "log_dir": "output/graph_edit/dm/mlp_mapper_bert_l8_pcae",
    "lr": 0.0001,
    "max_edge_level": 1,
    "min_lr": 1e-06,
    "model": "mlp_mapper_bert_l8",
    "num_workers": 8,
    "output_dir": "output/graph_edit/dm/mlp_mapper_bert_l8_pcae",
    "pin_mem": true,
    "plateau_scheduler": false,
    "point_cloud_size": 2048,
    "rank": 0,
    "resume": "",
    "resume_full_weights": false,
    "resume_weights": false,
    "seed": 0,
    "start_epoch": 0,
    "text_model_name": "bert-base-uncased",
    "use_adam": false,
    "use_clip": false,
    "use_embeds": true,
    "valid_step": 5,
    "wandb_id": null,
    "warmup_epochs": 40,
    "weight_decay": 0.05,
    "world_size": 4
}
[01:01:05.253017] Job dir: /ibex/user/slimhy/Shape2VecSet/code
[01:01:05.254667] |Train| size = [228000]
[01:01:05.255040] |Valid| size = [2976]
[01:01:06.473020] Model = MLPLatentMapper(
  (dir_mlp): MLP(
    (net): Sequential(
      (0): Linear(in_features=4864, out_features=4096, bias=True)
      (1): BatchNorm1d(4096, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Dropout(p=0.2, inplace=False)
      (4): Linear(in_features=4096, out_features=4096, bias=True)
      (5): BatchNorm1d(4096, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): ReLU(inplace=True)
      (7): Dropout(p=0.2, inplace=False)
      (8): Linear(in_features=4096, out_features=4096, bias=True)
      (9): BatchNorm1d(4096, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (10): ReLU(inplace=True)
      (11): Dropout(p=0.2, inplace=False)
      (12): Linear(in_features=4096, out_features=4096, bias=True)
      (13): BatchNorm1d(4096, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (14): ReLU(inplace=True)
      (15): Dropout(p=0.2, inplace=False)
      (16): Linear(in_features=4096, out_features=4096, bias=True)
      (17): BatchNorm1d(4096, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (18): ReLU(inplace=True)
      (19): Dropout(p=0.2, inplace=False)
      (20): Linear(in_features=4096, out_features=4096, bias=True)
      (21): BatchNorm1d(4096, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (22): ReLU(inplace=True)
      (23): Dropout(p=0.2, inplace=False)
      (24): Linear(in_features=4096, out_features=4096, bias=True)
      (25): BatchNorm1d(4096, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (26): ReLU(inplace=True)
      (27): Dropout(p=0.2, inplace=False)
      (28): Linear(in_features=4096, out_features=4096, bias=False)
    )
  )
  (mag_mlp): MLP(
    (net): Sequential(
      (0): Linear(in_features=4864, out_features=256, bias=True)
      (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Dropout(p=0.2, inplace=False)
      (4): Linear(in_features=256, out_features=128, bias=True)
      (5): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): ReLU(inplace=True)
      (7): Dropout(p=0.2, inplace=False)
      (8): Linear(in_features=128, out_features=64, bias=True)
      (9): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (10): ReLU(inplace=True)
      (11): Dropout(p=0.2, inplace=False)
      (12): Linear(in_features=64, out_features=1, bias=False)
    )
  )
)
[01:01:06.493999] Params (M): 138.74
wandb: Currently logged in as: habib-slim (shapewalk). Use `wandb login --relogin` to force relogin
wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: wandb version 0.16.0 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.12
wandb: Run data is saved locally in /ibex/user/slimhy/Shape2VecSet/wandb/run-20231114_010110-7qvn84y2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mlp_mapper_bert_l8_pcae__cyj52vq2
wandb: ‚≠êÔ∏è View project at https://wandb.ai/shapewalk/shape2vecset
wandb: üöÄ View run at https://wandb.ai/shapewalk/shape2vecset/runs/7qvn84y2
[01:01:17.850112] Model params:
 {
    "accum_iter": 1,
    "base_blr": 0.0001,
    "batch_size": 32,
    "clip_grad": 3.0,
    "dist_eval": true,
    "eff_batch_size": 128,
    "epochs": 800,
    "eval": false,
    "layer_decay": 0.75,
    "lr": 0.0001,
    "max_edge_level": 1,
    "min_lr": 1e-06,
    "model": "mlp_mapper_bert_l8",
    "resume": "",
    "resume_full_weights": false,
    "start_epoch": 0,
    "weight_decay": 0.05
}
[01:01:17.884998] Start training for 800 epochs
Traceback (most recent call last):
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 586, in <module>
Traceback (most recent call last):
[01:01:20.531374]   File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 586, in <module>
    main(args)
    main(args)
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 517, in main
Traceback (most recent call last):
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 517, in main
    train_stats = train_func(
  File "/ibex/user/slimhy/Shape2VecSet/code/engine_node2node.py", line 133, in train_one_epoch
    train_stats = train_func([01:01:20.533496] 
    loss = forward_pass(
  File "/ibex/user/slimhy/Shape2VecSet/code/engine_node2node.py", line 91, in forward_pass
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 586, in <module>
    main(args)
  File "/ibex/user/slimhy/Shape2VecSet/code/engine_node2node.py", line 133, in train_one_epoch
    loss = criterion(model, embeds_node_a, embeds_node_b, embeds_text_ab)
  File "/ibex/user/slimhy/Shape2VecSet/code/losses/mapper_loss.py", line 27, in __call__
    [01:01:20.534887] loss = forward_pass(
    edit_vec = net(x_a, embed_ab)
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 517, in main
    train_stats = train_func(
  File "/ibex/user/slimhy/Shape2VecSet/code/engine_node2node.py", line 91, in forward_pass
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    [01:01:20.536048] loss = criterion(model, embeds_node_a, embeds_node_b, embeds_text_ab)
  File "/ibex/user/slimhy/Shape2VecSet/code/engine_node2node.py", line 133, in train_one_epoch
    loss = forward_pass(
  File "/ibex/user/slimhy/Shape2VecSet/code/losses/mapper_loss.py", line 27, in __call__
    [01:01:20.536777] return forward_call(*args, **kwargs)
    edit_vec = net(x_a, embed_ab)
  File "/ibex/user/slimhy/Shape2VecSet/code/engine_node2node.py", line 91, in forward_pass
    loss = criterion(model, embeds_node_a, embeds_node_b, embeds_text_ab)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
[01:01:20.537900]   File "/ibex/user/slimhy/Shape2VecSet/code/losses/mapper_loss.py", line 27, in __call__
    edit_vec = net(x_a, embed_ab)
    return forward_call(*args, **kwargs)[01:01:20.538389] 
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    [01:01:20.539617] return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
    return forward_call(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
  File "/ibex/user/slimhy/Shape2VecSet/code/models/mlp_mapper.py", line 132, in forward
[01:01:20.541072]     dir_vec = self.dir_mlp(x)
  File "/ibex/user/slimhy/Shape2VecSet/code/models/mlp_mapper.py", line 91, in __call__
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
    return self.net(x)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
[01:01:20.542662]     return forward_call(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
    return forward_call(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
  File "/ibex/user/slimhy/Shape2VecSet/code/models/mlp_mapper.py", line 132, in forward
[01:01:20.543744]     dir_vec = self.dir_mlp(x)
  File "/ibex/user/slimhy/Shape2VecSet/code/models/mlp_mapper.py", line 132, in forward
    dir_vec = self.dir_mlp(x)
  File "/ibex/user/slimhy/Shape2VecSet/code/models/mlp_mapper.py", line 91, in __call__
    input = module(input)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    [01:01:20.545003] return self.net(x)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
  File "/ibex/user/slimhy/Shape2VecSet/code/models/mlp_mapper.py", line 91, in __call__
    return self.net(x)
    return forward_call(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
[01:01:20.546429]     return F.linear(input, self.weight, self.bias)
    input = module(input)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x1024 and 4864x4096)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
[01:01:20.547963]   File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
    return forward_call(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
[01:01:20.548613]     return F.linear(input, self.weight, self.bias)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x1024 and 4864x4096)
[01:01:20.549671]   File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
[01:01:20.550258] RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x1024 and 4864x4096)
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
Traceback (most recent call last):
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 586, in <module>
    main(args)
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 517, in main
    train_stats = train_func(
  File "/ibex/user/slimhy/Shape2VecSet/code/engine_node2node.py", line 133, in train_one_epoch
    loss = forward_pass(
  File "/ibex/user/slimhy/Shape2VecSet/code/engine_node2node.py", line 91, in forward_pass
    loss = criterion(model, embeds_node_a, embeds_node_b, embeds_text_ab)
  File "/ibex/user/slimhy/Shape2VecSet/code/losses/mapper_loss.py", line 27, in __call__
    edit_vec = net(x_a, embed_ab)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ibex/user/slimhy/Shape2VecSet/code/models/mlp_mapper.py", line 132, in forward
    dir_vec = self.dir_mlp(x)
  File "/ibex/user/slimhy/Shape2VecSet/code/models/mlp_mapper.py", line 91, in __call__
    return self.net(x)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x1024 and 4864x4096)
wandb: üöÄ View run mlp_mapper_bert_l8_pcae__cyj52vq2 at: https://wandb.ai/shapewalk/shape2vecset/runs/7qvn84y2
wandb: Ô∏è‚ö° View job at https://wandb.ai/shapewalk/shape2vecset/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjExMTIyMDEzMQ==/version_details/v19
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231114_010110-7qvn84y2/logs
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 106579 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 106580) of binary: /home/slimhy/conda/envs/shape2vecset/bin/python3.10
Traceback (most recent call last):
  File "/home/slimhy/conda/envs/shape2vecset/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
code/main_node2node.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-14_01:01:27
  host      : gpu214-10.ibex.kaust.edu.sa
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 106581)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-11-14_01:01:27
  host      : gpu214-10.ibex.kaust.edu.sa
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 106582)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-14_01:01:27
  host      : gpu214-10.ibex.kaust.edu.sa
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 106580)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
